# .github/workflows/main.yml

name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint with Flake8
        run: |
          flake8 . --count --show-source --statistics

      - name: Check formatting with Black
        run: |
          black --check .

      - name: Static type checking with MyPy
        run: |
          mypy pyreliabilitypro --ignore-missing-imports

      - name: Run tests with Pytest
        run: |
          pytest