# .github/workflows/publish.yml

name: Publish Python Package to PyPI

# This workflow runs ONLY when a new GitHub Release is created and published.
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Grant permissions for the pypa/gh-action-pypi-publish action to get a token.
    permissions:
      id-token: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # Use a generic recent Python version

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build package distributions
        run: python -m build

      # --- THIS IS THE STEP YOU WILL UNCOMMENT FOR YOUR FIRST TEST ---
      # This step publishes to TestPyPI. It's a "dry run" for your first release.
      #- name: Publish package to TestPyPI
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    # Use the API token you created for TestPyPI and stored as a GitHub secret
      #    password: ${{ secrets.TEST_PYPI_API_TOKEN }}
      #    # Specify the TestPyPI repository URL
      #    repository_url: https://test.pypi.org/legacy/

      # --- THIS STEP SHOULD BE COMMENTED OUT FOR YOUR FIRST TEST ---
      # After you confirm TestPyPI works, you will comment out the step above
      # and uncomment this one for your real release.
      - name: Publish package to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           # Use the API token for the real PyPI stored as a GitHub secret
           password: ${{ secrets.PYPI_API_TOKEN }}